# Generated by Django 4.1.7 on 2025-04-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('api_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_client', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=10000)),
                ('journal_name', models.CharField(max_length=10000)),
                ('call', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.IntegerField()),
                ('code_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Facts_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_id', models.IntegerField()),
                ('id_ip', models.IntegerField()),
                ('id_type', models.IntegerField()),
                ('id_API', models.IntegerField()),
                ('id_protocol', models.IntegerField()),
                ('id_result', models.IntegerField()),
                ('id_referer', models.IntegerField()),
                ('id_data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Protocol_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=10000)),
                ('p_version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.IntegerField()),
                ('ref_name', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Request_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('id_code', models.IntegerField()),
                ('result_time', models.TimeField()),
                ('result_byte', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agent', models.IntegerField()),
                ('id_ip', models.IntegerField()),
                ('os', models.CharField(max_length=1000)),
                ('krnl', models.CharField(max_length=1000)),
                ('ren_eng', models.CharField(max_length=1000)),
                ('eng_ver', models.CharField(max_length=100)),
                ('html_cmpbl', models.CharField(max_length=10000)),
                ('browser', models.CharField(max_length=10000)),
                ('browser_ver', models.CharField(max_length=100)),
            ],
        ),
    ]
