# Generated by Django 5.2 on 2025-04-21 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_type',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'log_files_code_type',
            },
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_name', models.CharField(max_length=400)),
            ],
            options={
                'unique_together': {('api_name',)},
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_client', models.CharField(max_length=20)),
                ('journal_name', models.CharField(max_length=10000)),
                ('user_id', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('ip_client', 'journal_name')},
            },
        ),
        migrations.CreateModel(
            name='Protocol_version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=10000)),
            ],
            options={
                'unique_together': {('p_name',)},
            },
        ),
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_name', models.CharField(max_length=10000)),
            ],
            options={
                'unique_together': {('ref_name',)},
            },
        ),
        migrations.CreateModel(
            name='Request_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('type_name',)},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_time', models.TimeField()),
                ('result_byte', models.IntegerField()),
                ('code', models.ForeignKey(blank=True, db_column='id_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_files.code_type')),
            ],
            options={
                'db_table': 'log_files_result',
            },
        ),
        migrations.CreateModel(
            name='User_agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('os', models.CharField(max_length=1000)),
                ('krnl', models.CharField(max_length=1000)),
                ('ren_eng', models.CharField(max_length=1000)),
                ('eng_ver', models.CharField(max_length=100)),
                ('html_cmpbl', models.CharField(max_length=10000)),
                ('browser', models.CharField(max_length=10000)),
                ('browser_ver', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('os', 'krnl', 'ren_eng', 'eng_ver', 'html_cmpbl', 'browser', 'browser_ver')},
            },
        ),
        migrations.CreateModel(
            name='Facts_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, max_length=400, null=True)),
                ('id_API', models.ForeignKey(blank=True, db_column='id_API', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_files.api')),
                ('id_client', models.ForeignKey(blank=True, db_column='id_client', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_files.clients')),
                ('id_protocol', models.ForeignKey(blank=True, db_column='id_protocol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_files.protocol_version')),
                ('id_referer', models.ForeignKey(blank=True, db_column='id_referer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_files.referer')),
                ('id_type', models.ForeignKey(blank=True, db_column='id_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_files.request_type')),
                ('id_result', models.ForeignKey(blank=True, db_column='id_result', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_files.result')),
                ('id_agent', models.ForeignKey(blank=True, db_column='id_agent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_files.user_agent')),
            ],
        ),
    ]
