# Generated by Django 4.1.7 on 2025-04-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_type',
            name='id',
        ),
        migrations.RemoveField(
            model_name='facts_table',
            name='id',
        ),
        migrations.RemoveField(
            model_name='protocol_version',
            name='id',
        ),
        migrations.RemoveField(
            model_name='referer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='request_type',
            name='id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_agent',
            name='id',
        ),
        migrations.AlterField(
            model_name='api',
            name='api_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='code_type',
            name='code_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facts_table',
            name='fact_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='protocol_version',
            name='protocol_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referer',
            name='ref_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request_type',
            name='type_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_agent',
            name='id_agent',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
