# Generated by Django 4.1.7 on 2025-04-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_files', '0002_remove_code_type_id_remove_facts_table_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='api',
            unique_together={('api_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='clients',
            unique_together={('ip_client', 'user_id', 'journal_name')},
        ),
        migrations.AlterUniqueTogether(
            name='code_type',
            unique_together={('code_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='protocol_version',
            unique_together={('p_name', 'p_version')},
        ),
        migrations.AlterUniqueTogether(
            name='referer',
            unique_together={('ref_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='request_type',
            unique_together={('type_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='user_agent',
            unique_together={('id_ip', 'os', 'krnl', 'ren_eng', 'eng_ver', 'html_cmpbl', 'browser', 'browser_ver')},
        ),
    ]
